.gitignore, build.sbt, logging/src/main/scala/com/ovoenergy/effect/Logging.scala, logging/src/test/scala/com/ovoenergy/effect/LoggingTest.scala, logging/version.sbt, project/build.properties, project/plugins.sbt
So this PR does the following
- Sets up multi project SBT so we can publish each utility into a separate jar
- Includes the basics for Bintray publishing + a version for each subproject
- Adds a logging type class (not 100% done yet but is a start)
The hope is to get this onto master & then set up a CircleCI build to release it.
=> PROP-1567 add Logging type class + project setup

.circleci/config.yml, build.sbt, currentTime/src/main/scala/com/ovoenergy/effect/CurrentTime.scala, logging/src/main/scala/com/ovoenergy/effect/Logging.scala, logging/version.sbt, project/plugins.sbt
So this looks a bit different to your average build due to us having (or soon to be having) several subprojects, independently versioned, in the same git repository.
I initially considered using sbt release as per usual but it occurred to me that we don't actually want to auto-increment the version, as to follow [semantic versioning](https://semver.org/) we'll want to alter the versions differently depending on what we've done.
As such this build process uses tags in the format `subproject/major.minor.patch` to identify + release versions of each subproject. The release process then will be the following
- Make delightful changes
- Merge them into master
- Create e.g. `logging/1.1.0` tag either with Github or the cli
- CircleCI will build + release `com.ovoenergy.effect.logging` to …
=> PROP-1567 Initial attempt at a CircleCI build

.circleci/config.yml
`git describe` does not like the unannotated tags created by the Github UI
I also tweaked the build a bit to stop if `git describe --tags` fails for whatever reason so we don't publish strangely versioned artifacts to bintray if things go wrong
=> Fix tag resolution not working

.scalafmt.conf, logging/src/main/scala/com/ovoenergy/effect/Logging.scala, logging/src/test/scala/com/ovoenergy/effect/LoggingTest.scala
Allows the `Logging.Error` case class to take a `String`, a `Throwable` or both.
=> Allow for logging of exceptions.

logging/src/main/scala/com/ovoenergy/effect/Logging.scala, logging/src/test/scala/com/ovoenergy/effect/LoggingTest.scala
I missed this initially, but the trace token should be added to the `MDC` automatically for logging purposes
=> Add the trace token to the MDC when logging

logging/src/main/scala/com/ovoenergy/effect/Logging.scala, logging/src/main/scala/com/ovoenergy/effect/TraceLogging.scala, logging/src/main/scala/com/ovoenergy/effect/Tracing.scala, logging/src/test/scala/com/ovoenergy/effect/LoggingTest.scala, logging/src/test/scala/com/ovoenergy/effect/TracingTest.scala
Okay so you may remember how originally in our apps `Tracing` and `Logging` were separate but then I merged them in this library...
Turns out that was a bad idea - we can't use `StateT` for tracing within FS2 streams but we still want to be able to log things in them, getting the tags to include from elsewhere.
With the merged type classes there was no way to represent that I could log within some effect but not see / modify tracing information, so this PR splits them into two and adds a third `TraceLogging` object with a tiny bit of syntax to tie them together when your `F[_]` does support both tracing and logging
This does make tracing / logging a bit more painful than it used to be (lots of `F[_]: Tracing: Logging`) but you'll see in future PRs elsewhere it means we can pass around …
=> Split tracing and logging

build.sbt, logging/src/main/scala/com/ovoenergy/effect/Logging.scala, logging/src/main/scala/com/ovoenergy/effect/TraceLogging.scala, logging/src/main/scala/com/ovoenergy/effect/Tracing.scala, logging/src/test/scala/com/ovoenergy/effect/LoggingTest.scala, logging/src/test/scala/com/ovoenergy/effect/TracingTest.scala, metrics-common/src/main/scala/com/ovoenergy/effect/Metrics.scala, metrics-datadog/src/main/scala/com/ovoenergy/effect/Datadog.scala, metrics-datadog/src/test/scala/com/ovoenergy/effect/DatadogTest.scala, metrics-kamon/src/main/scala/com/ovoenergy/effect/Kamon.scala, metrics-kamon/src/test/scala/com/ovoenergy/effect/MetricsTest.scala
This PR
- Splits the `Metrics` trait out into its own jar so we can use it across implementations
- Adds a minimal datadog implementation that sends metrics over UDP to DogStatsD
- Bumps some dependency versions
=> Datadog metrics

metrics-datadog/src/main/scala/com/ovoenergy/effect/Datadog.scala
I forgot that the `config.agentHost` should not be used when opening the socket, only when sending packets
=> Fix bind error

.circleci/config.yml, .gitignore, build.sbt, logging/src/main/scala/com/ovoenergy/effect/Logging.scala, metrics-kamon/src/main/scala/com/ovoenergy/effect/Kamon.scala, natchez-datadog/src/main/scala/com/ovoenergy/effect/natchez/DatadogSpan.scala, natchez-datadog/src/test/scala/com/ovoenergy/effect/natchez/DatadogTest.scala, natchez-slf4j/src/test/scala/com/ovoenergy/effect/natchez/Slf4jSpanTest.scala
The project I'm working on uses Scala 2.13, so if I'm going to use the magical Datadog code contained herein, I need to build this library for 2.13. I had to upgrade a few dependency versions as well because the versions used before weren't all available for 2.13.
This is simpler than cross-building, and if anyone needs new features from this library, then they can upgrade to 2.12 (sorry to those people).
=> Upgrade to 2.13

metrics-kamon/src/main/scala/com/ovoenergy/effect/Kamon.scala
Thanks to @voidcontext and @ericaovo :)
=> Nicer syntax for avoiding discarded non-unit value warning

build.sbt, natchez-log4cats/src/main/scala/com/ovoenergy/effect/TracedLogger.scala
This is a small integration between Natchez & log4cats to allow us to pull headers from the Natchez `kernel` into the log4cats MDC so that in Datadog logs can be correlated with metrics
I didn't write any tests since this is so small, please forgive me!
=> Natchez log4cats

natchez-datadog/src/main/scala/com/ovoenergy/effect/natchez/Datadog.scala, natchez-datadog/src/main/scala/com/ovoenergy/effect/natchez/DatadogSpan.scala, natchez-datadog/src/main/scala/com/ovoenergy/effect/natchez/DatadogTags.scala, natchez-datadog/src/main/scala/com/ovoenergy/effect/natchez/SubmittableSpan.scala, natchez-datadog/src/test/scala/com/ovoenergy/effect/natchez/DatadogTest.scala, natchez-doobie/src/main/scala/com/ovoenergy/effect/natchez/TracedTransactor.scala, natchez-doobie/src/test/scala/com/ovoenergy/effect/natchez/TracedTransactorTest.scala, natchez-http4s/src/main/scala/com/ovoenergy/effect/natchez/http4s/server/Configuration.scala, natchez-http4s/src/test/scala/com/ovoenergy/effect/natchez/http4s/server/TraceMiddlewareTest.scala
This PR does three things
- Maps a `span.type` tag into a `type` field on when we submit traces to Datadog
- Adds a magic metric that _should_ prevent Datadog only keeping a sample of our traces\*
- Adds an `X-DataDog-Trace-Count` header to stop the agent logging warnings all the time
\* This could be made configurable in the future but none of the services using this library to my knowledge have enough traffic to require us to drop some traces
=> Support span.type, prevent Datadog sampling traces

README.md, build.sbt, natchez-datadog/src/main/scala/com/ovoenergy/effect/natchez/SubmittableSpan.scala, natchez-doobie/src/main/scala/com/ovoenergy/effect/natchez/TracedTransactor.scala, natchez-fs2/src/main/scala/com/ovoenergy/effect/natchez/AllocatedSpan.scala, natchez-fs2/src/main/scala/com/ovoenergy/effect/natchez/syntax.scala, natchez-fs2/src/test/scala/com/ovoenergy/effect/natchez/AllocatedSpanTest.scala, natchez-http4s/src/main/scala/com/ovoenergy/effect/natchez/http4s/server/Configuration.scala, natchez-http4s/src/main/scala/com/ovoenergy/effect/natchez/http4s/server/TraceMiddleware.scala, natchez-testkit/src/main/scala/com/ovoenergy/effect/natchez/TestEntryPoint.scala
These modules are a bit more experimental than the others but what `natchez-fs2` does is break `Span[F]` out of a `Resource[F, Span[F]]` and give you an `AllocatedSpan` that can be manually submitted as part of an FS2 stream, much like a committable Kafka Record in fs2-kafka
=> Add natchez-fs2 & natchez-testkit

build.sbt, natchez-datadog/src/main/scala/com/ovoenergy/effect/natchez/Datadog.scala, natchez-datadog/src/test/scala/com/ovoenergy/effect/natchez/DatadogTest.scala, natchez-datadog/src/test/scala/com/ovoenergy/effect/natchez/TestClient.scala
This PR
- Adds an optional `agentHost` param for situations where the Datadog agent isn't running locally
- Warns when traces can't be submitted to Datadog or if the agent responds with a non 200
- Fixes the submitter stopping permanently if a submission to Datadog fails
=> Make agent host configurable, add error handling to submitter

README.md, build.sbt
Does what it says on the tin. h2 has some licensing issues but we only use it for tests.
=> Remove doobie-h2 dependency + fix publishing

README.md
Noticed that http4s wasn't in the readme for moving to new repo the same way as the others.
=> convenient update to readme for how to update http4s

.circleci/config.yml, natchez-extras-datadog/src/main/scala/com/ovoenergy/natchez/extras/datadog/DatadogTags.scala, natchez-extras-datadog/src/main/scala/com/ovoenergy/natchez/extras/datadog/SpanIdentifiers.scala, natchez-extras-datadog/src/main/scala/com/ovoenergy/natchez/extras/datadog/SubmittableSpan.scala, natchez-extras-datadog/src/main/scala/com/ovoenergy/natchez/extras/datadog/data/UnsignedLong.scala, natchez-extras-datadog/src/main/scala/com/ovoenergy/natchez/extras/datadog/headers/HeaderInstances.scala, natchez-extras-datadog/src/main/scala/com/ovoenergy/natchez/extras/datadog/headers/TraceHeaders.scala, natchez-extras-datadog/src/test/scala/com/ovoenergy/natchez/extras/datadog/DatadogTest.scala, natchez-extras-datadog/src/test/scala/com/ovoenergy/natchez/extras/datadog/SpanIdentifiersTest.scala, natchez-extras-datadog/src/test/scala/com/ovoenergy/natchez/extras/datadog/data/UnsignedLongTest.scala, natchez-extras-datadog/src/test/scala/com/ovoenergy/natchez/extras/datadog/headers/TraceHeadersTest.scala
This PR adds support for propagating traces through B3 headers detailed [in this doc](https://github.com/openzipkin/b3-propagation)
It also makes the handling of trace IDs a bit more robust & fixes some bugs with how they were handled previously by introducing an `UnsignedLong` wrapper that ensures we treat trace IDs as being unsigned and serialise them properly. The old code, for example, called `abs` on a random `long` when generating the trace IDs which means it would've only used half of the possible values of the long.
I've also fixed an issue with the `_sampling_priority_v1` metric we send to force Datadog to keep all traces - there was an extra leading underscore and it only needs to be attached to the root span.
=> B3 propagation

docs/docs/docs/natchez-datadog.md, natchez-extras-http4s/src/test/scala/com/ovoenergy/natchez/extras/http4s/client/TracedClientTest.scala, natchez-extras-testkit/src/main/scala/com/ovoenergy/natchez/extras/testkit/TestEntryPoint.scala, natchez-extras-testkit/src/test/scala/com/ovoenergy/natchez/extras/testkit/TestEntryPointTest.scala
This fixes a long standing annoyance with `TestEntryPoint` which was that it didn't keep track of any tags submitted to the spans it created. Now it does so tests can be written that ensure applications are sending the right tags along to Natchez.
I renamed `TestSpan` to `CompletedSpan` to make it clearer that spans are only available for inspection by tests after they've been completed and I inlined the creation of spans & resource handling because the two separate functions confused me at first.
=> Record submitted tags in TestEntryPoint

build.sbt, natchez-extras-datadog/src/test/scala/com/ovoenergy/natchez/extras/datadog/DatadogTest.scala, natchez-extras-datadog/src/test/scala/com/ovoenergy/natchez/extras/datadog/SpanIdentifiersTest.scala, natchez-extras-datadog/src/test/scala/com/ovoenergy/natchez/extras/datadog/data/UnsignedLongTest.scala, natchez-extras-datadog/src/test/scala/com/ovoenergy/natchez/extras/datadog/headers/TraceHeadersTest.scala, natchez-extras-dogstatsd/src/test/scala/com/ovoenergy/natchez/extras/dogstatsd/DatadogTest.scala, natchez-extras-doobie/src/test/scala/com/ovoenergy/natchez/extras/doobie/TracedTransactorTest.scala, natchez-extras-fs2/src/test/scala/com/ovoenergy/natchez/extras/fs2/AllocatedSpanTest.scala, natchez-extras-http4s/src/test/scala/com/ovoenergy/natchez/extras/http4s/client/TracedClientTest.scala, natchez-extras-http4s/src/test/scala/com/ovoenergy/natchez/extras/http4s/server/SyntaxTest.scala, natchez-extras-http4s/src/test/scala/com/ovoenergy/natchez/extras/http4s/server/TraceMiddlewareTest.scala, natchez-extras-slf4j/src/test/scala/com/ovoenergy/natchez/extras/slf4j/Slf4jSpanTest.scala, natchez-extras-testkit/src/test/scala/com/ovoenergy/natchez/extras/testkit/TestEntryPointTest.scala
I'm doing this because MUnit has nice built in case class diffs so we can remove Claimant, which is deprecated and not available for Scala 3
=> Move to MUnit

build.sbt
The core package contains some code that might be used by the consumers of this library so it should be published. I am making this change on main so that we can release it quickly for the `v6.x` line, then it can be reintegrated into the `scala-3` branch. 
Issue: #84
=> Publish natchez-extras-core package

natchez-extras-http4s/src/main/scala/com/ovoenergy/natchez/extras/http4s/client/TracedClient.scala, natchez-extras-http4s/src/main/scala/com/ovoenergy/natchez/extras/http4s/server/TraceMiddleware.scala
- optionally override the default 'removeNumericPathSegments' functionality by providing a function that does the redaction.
- `natchez-extras` should fall back to the current implementation when the function is not provided to keep backward compatibility
=> Make 'removeNumericPathSegments' method substitutable

natchez-extras-datadog/src/main/scala/com/ovoenergy/natchez/extras/datadog/SubmittableSpan.scala, natchez-extras-datadog/src/test/scala/com/ovoenergy/natchez/extras/datadog/DatadogTest.scala
This PR fixes an unexpected behaviour: when error information was manually added to the span tags, the error was displayed in the trace details, but the span itself wasn't flagged as erroneous.
=> Set the Datadog span's error flag, when its meta has an error message

.gitignore, build.sbt, natchez-ce3/src/main/scala/com/ovoenergy/natchez/extras/combine/ce3/IOLocalEntrypoint.scala, natchez-ce3/src/main/scala/com/ovoenergy/natchez/extras/combine/ce3/IOLocalTrace.scala, natchez-ce3/src/test/scala/com/ovoenergy/natchez/extras/combine/ce3/IOLocalEntrypointTest.scala, natchez-ce3/src/test/scala/com/ovoenergy/natchez/extras/combine/ce3/TestSpan.scala, natchez-extras-combine/src/main/scala/com/ovoenergy/natchez/extras/combine/Combine.scala, natchez-extras-datadog/src/main/scala/com/ovoenergy/natchez/extras/datadog/Datadog.scala, natchez-extras-datadog/src/main/scala/com/ovoenergy/natchez/extras/datadog/DatadogSpan.scala, natchez-extras-datadog/src/main/scala/com/ovoenergy/natchez/extras/datadog/SpanIdentifiers.scala, natchez-extras-datadog/src/test/scala/com/ovoenergy/natchez/extras/datadog/DatadogTest.scala, natchez-extras-datadog/src/test/scala/com/ovoenergy/natchez/extras/datadog/SpanIdentifiersTest.scala, natchez-extras-doobie/src/test/scala/com/ovoenergy/natchez/extras/doobie/TracedTransactorTest.scala, natchez-extras-fs2/src/main/scala/com/ovoenergy/natchez/extras/fs2/AllocatedSpan.scala, natchez-extras-fs2/src/main/scala/com/ovoenergy/natchez/extras/fs2/syntax.scala, natchez-extras-http4s/src/main/scala/com/ovoenergy/natchez/extras/http4s/client/TracedClient.scala, natchez-extras-http4s/src/main/scala/com/ovoenergy/natchez/extras/http4s/server/TraceMiddleware.scala, natchez-extras-http4s/src/test/scala/com/ovoenergy/natchez/extras/http4s/client/TracedClientTest.scala, natchez-extras-log4cats/src/main/scala/com/ovoenergy/natchez/extras/log4cats/TracedLogger.scala, natchez-extras-slf4j/src/main/scala/com/ovoenergy/natchez/extras/slf4j/Slf4j.scala, natchez-extras-slf4j/src/main/scala/com/ovoenergy/natchez/extras/slf4j/Slf4jSpan.scala, natchez-extras-slf4j/src/test/scala/com/ovoenergy/natchez/extras/slf4j/Slf4jSpanTest.scala, natchez-extras-testkit/src/main/scala/com/ovoenergy/natchez/extras/testkit/TestEntryPoint.scala, natchez-extras-testkit/src/test/scala/com/ovoenergy/natchez/extras/testkit/TestEntryPointTest.scala, project/build.properties
Hi!
I'm trying to bump natchez to the latest version.
I'm unsure whether there are binary incompatibilities here.
Also, I'm not an expert in Datadog tracing, so I'd need a double check on that part.
=> upgrade to natchez 0.3.x

build.sbt, natchez-extras-log4cats/src/main/scala/com/ovoenergy/natchez/extras/log4cats/TracedLogger.scala
This is the most specific log4cats logger trait, which is what is used by the new LoggerFactory machinery. Without this it is very awkward to use TracedLogger with LoggerFactory
=> Update TracedLogger to use SelfAwareStructuredLogger trait

build.sbt, docs/docs/docs/natchez-doobie.md, natchez-extras-doobie-legacy/src/main/scala/com/ovoenergy/natchez/extras/doobie/TracedStatement.scala, natchez-extras-doobie-legacy/src/main/scala/com/ovoenergy/natchez/extras/doobie/TracedTransactor.scala, natchez-extras-doobie-legacy/src/test/scala/com/ovoenergy/natchez/extras/doobie/TracedTransactorTest.scala, natchez-extras-doobie/src/main/scala/com/ovoenergy/natchez/extras/doobie/TracedTransactor.scala, project/build.properties
Bumping doobie to the latest RC4.
Since this is a breaking change, I implemented the proposal from https://github.com/ovotech/natchez-extras/pull/108#issuecomment-1666796394 and added a "doobie legacy" module, to allow library bumps (because of natchez changes) without the need of the doobie migration. It is intended to be removed with the next release cycle (9.0.0?).
Cherry-picked the implementation for RC4 from https://github.com/ovotech/natchez-extras/pull/108.
=> Doobie rc4

natchez-extras-doobie/src/main/scala/com/ovoenergy/natchez/extras/doobie/TracedStatement.scala, natchez-extras-doobie/src/main/scala/com/ovoenergy/natchez/extras/doobie/TracedTransactor.scala, natchez-extras-doobie/src/test/scala/com/ovoenergy/natchez/extras/doobie/TracedTransactorTest.scala
I was having trouble tracing `updates` using `withUniqueGeneratedKeys`, these changes appear to have solved the problem so far.
=> fix: add traces to updates with generared keys
